name: 'Pip Upload'
description: 'build & upload pip package'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  deps_list:
    description: file containing dependencies (accepted by pip install -r) -- use NONE if you do not need to install dependencies
    required: true
    default: requirements.txt
  setup:
    description: setup script
    required: true
    default: setup.py
  username:
    description: pip username
    required: true
    default: __token__
  password:
    description: pip password
    required: true
  path:
    description: path of git repo relative to GITHUB_WORKSPACE (no trailing slash)
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.deps_list }}
    - ${{ inputs.setup }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
